check for pkg-config before anything (fix bogus missing libraries failure)

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -20,6 +20,14 @@ dnl Dependencies
 LIBNFNETLINK_REQUIRED=0.0.32
 LIBNETFILTER_CONNTRACK_REQUIRED=0.0.91
 
+AC_CHECK_PROG(HAVE_PKG_CONFIG, pkg-config, yes)
+if test "x$HAVE_PKG_CONFIG" = "x"
+then
+	echo "*** Error: No suitable pkg-config found. ***"
+	echo "    Please install the 'pkg-config' package."
+	exit 1
+fi
+
 PKG_CHECK_MODULES(LIBNFNETLINK, libnfnetlink >= $LIBNFNETLINK_REQUIRED,,
         AC_MSG_ERROR(Cannot find libnfnetlink >= $LIBNFNETLINK_REQUIRED))
 
